#!/usr/bin/env python

import os
import json
import argparse
import logging

import pika
import yaml

from git_slack import slack, response

logger = logging.getLogger(__name__)


if __name__ == '__main__':
    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description='Post Git push information from AMQP to Slack')
    parser.add_argument('--config', metavar='file',
                        help='Configuration file')
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    # Load configuration file
    if args.config:
        with open(args.config, 'r') as f:
            config = yaml.load(f)
    else:
        config = {}

    server_host = os.environ.get('AMQP_PORT_5672_TCP_ADDR', 'localhost')
    server_port = int(os.environ.get('AMQP_PORT_5672_TCP_PORT', '5672'))

    connection_params = pika.ConnectionParameters(host=server_host,
                                                  port=server_port)
    connection = pika.BlockingConnection(connection_params)
    channel = connection.channel()

    channel.exchange_declare(exchange='git', type='topic')

    result = channel.queue_declare(exclusive=True)
    queue_name = result.method.queue

    channel.queue_bind(exchange='git',
                       queue=queue_name,
                       routing_key='#')

    # Run Slack WebHook connector
    if 'slack' in config and 'webhook_url' in config['slack']:
        logger.info('Using Slack WebHook URL: {}'.format(
            config['slack']['webhook_url']))
        hook = slack.SlackWebHook(config['slack']['webhook_url'])
        hook.start()
    else:
        logger.warning('No Slack URL defined! No messages will be sent.')
        logger.warning('Set "slack.webhook_url" in the configuration' +
                       ' file to enable Slack messages.')
        hook = None

    # Define Slack message options
    slack_username = None
    slack_channel = None
    if 'slack' in config:
        if 'username' in config['slack']:
            slack_username = str(config['slack']['username'])
        if 'channel' in config['slack']:
            slack_channel = str(config['slack']['channel'])

    # Callback on Git push messages
    def callback(ch, method, properties, body):
        push = json.loads(body)
        message = response.message_from_push(push)

        if message is not None and hook is not None:
            hook.enqueue(message)

    channel.basic_consume(callback,
                          queue=queue_name,
                          no_ack=True)

    logger.info("Waiting for Git push messages...")
    try:
        channel.start_consuming()
    except KeyboardInterrupt:
        pass
    finally:
        if hook is not None:
            logger.info('Stopping Slack WebHook connector...')
            hook.stop()

        logger.info('Closing AMQP connection...')
        connection.close()

    logger.info('Done.')
